using LinkedList;
Console.WriteLine("Welcome to the linked list");
linked_list List = new linked_list();
List.create(56);
//List.append(30);
//List.append(70);
//List.append(45);
//List.append(63);
//List.append(78);
//Console.WriteLine("Before deletion of the last node ");
List.print();
List.search(45);
//Console.WriteLine("After deletion of the last node ");
//List.print();
